# Copy this file to application-local.properties for local development.
# Keep application-local.properties untracked.
#razorpay.key.id=your_test_key_id
#razorpay.key.secret=your_test_key_secret
# Razorpay API Credentials
razorpay.key.id=rzp_test_mbinFkvUx9Ur9V
razorpay.key.secret=4X4ksgXdCHZKNlF5jTMUF8wD